### PR TITLE
Added bower.json

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/tamble/jquery-ui-daterangepicker/issues/27, opted to take the simplest name possible :+1:

### CODE REVIEW

**Comment by ghola** [comment]
Does bower support dependency versioning similar to composer's '~' ? I'm asking because the widget may not be compatible with latest versions of it's dependencies so we would need to make sure that we at least restrict them to a range for the current major version (a new major version is sure to introduce breaking changes).

**Comment by holtkamp** [comment]
When look at [the example](http://bower.io/docs/creating-packages/#bowerjson-example) and the [section referring to SemVer](http://bower.io/docs/creating-packages/#version), it does support the tilde notation.

So you opt for the following approach?:

```json
"dependencies": {
    "jquery": "~1.8.3",
    "jquery-ui": "~1.9.0",
    "momentjs": "~2.3.0"
}
```

**Comment by ghola** [comment]
Yes, let's use that notation.

**Comment by ghola** [comment]
Can you please squash the 3 commits into a single one?

**Comment by holtkamp** [comment]
Uhm... "why" would I do that? It is a single PR with a clear purpose that can be merged at once right?

or am I missing something?

**Comment by ghola** [comment]
Squashing preserves a better git history as it removes pollutant commits. We use that practice for our internal development and we intend to keep it for our public repo too. If you want additional arguments for this practice you can find some here: http://programmers.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests

**Comment by holtkamp** [comment]
Thanks, just learned something new, did as requested, but it seems some old commits are prepended to the PR now, not sure how that happened...

**Comment by ghola** [comment]
You seem to have rebased your branch on master instead of keeping it on devel. Anyway, i corrected it and now it should be fine.

**Pull request merged**
