### PR TITLE
call reset() on $mask.click

### PR DESCRIPTION
**Pull request by ahawryla**
1. select any value in a datepicker
2. open the datepicker again and mark another value, click 'cancel' button
3. open the datepicker again - you will see a value selected in point 1.
4. select another value and click somewhere outside the datepicker
5. open datepicker again - you will see that value from point 4. is marked (getRange will still return value from point 1)

solution: in $mask.click call both close and reset function as it is done for 'cancel' button click handler

### CODE REVIEW

**Comment by op16** [comment]
So you are arguing that a click somewhere outside the daterangepicker should mean "Cancel", and not just "hide the daterangepicker (and maybe I'll decide later to click Apply or Cancel)"?

The current semantics looks fine to me. Still your proposal might be better.

**Comment by ahawryla** [comment]
Yes, I do. Right now, in situation described in points 4 and 5 above, there is an inconsistency between what a user can see and what he actually have selected and it may be confusing.

**Comment by op16** [comment]
OK, if you want consistency, the same behaviour is needed when the user presses Escape (line 607). If you modify your PR, we'll merge it.

**Comment by op16** [comment]
And let's not forget clicking the trigger button (toggle - line 644).

**Comment by ahawryla** [comment]
I've added reset() also to places indicated by you. Thanks for pointing them out!

**Comment by ahawryla** [comment]
Thanks a lot! :)

**Comment by op16** [comment]
Thank you for your contribution!

**Pull request merged**
